### Loading the raw dataset into a dataframe

In [2]:
import pandas as pd

path = "../data/raw/kathmandu_full_raw_2023_2024.csv"

data = pd.read_csv(path)

In [3]:
data.shape

(17544, 12)

In [4]:
data.sample(5)

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,surface_pressure
10078,2/24/2024 22:00,33.1,48.5,670,16.3,8.2,86,5.7,72,1.1,180,871.5
3506,5/27/2023 2:00,33.8,49.1,522,16.6,2.7,77,15.9,96,4.7,148,867.2
1567,3/7/2023 7:00,34.1,48.9,490,10.2,5.2,90,13.6,76,6.5,146,874.0
3224,5/15/2023 8:00,44.9,66.6,346,2.0,2.8,165,21.0,67,5.9,281,869.8
13522,7/17/2024 10:00,11.7,16.6,218,3.3,2.5,82,25.9,76,1.8,323,869.5

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  17544 non-null  str
 1   pm2_5                 17544 non-null  float64
 2   pm10                  17544 non-null  float64
 3   carbon_monoxide       17544 non-null  int64
 4   nitrogen_dioxide      17544 non-null  float64
 5   sulphur_dioxide       17544 non-null  float64
 6   ozone                 17544 non-null  int64
 7   temperature_2m        17544 non-null  float64
 8   relative_humidity_2m  17544 non-null  int64
 9   wind_speed_10m        17544 non-null  float64
 10  wind_direction_10m    17544 non-null  int64
 11  surface_pressure      17544 non-null  float64
dtypes: float64(7), int64(4), str(1)
memory usage: 1.6 MB

In [6]:
data.describe()

,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,surface_pressure
count,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000
mean,30.664689,43.707974,612.107045,12.572458,6.137454,96.054891,18.154799,74.586069,4.494921,202.288703,870.526813
std,19.408556,24.614492,421.671717,11.520046,4.086209,35.692174,5.896066,20.973804,2.831807,77.789930,3.355115
min,0.400000,0.500000,87.000000,0.000000,0.000000,9.000000,0.800000,9.000000,0.000000,2.000000,860.000000
25%,17.500000,25.575000,314.000000,3.500000,3.500000,67.000000,13.800000,60.000000,2.500000,153.000000,868.200000
50%,26.100000,38.400000,477.000000,9.500000,5.200000,93.000000,19.100000,79.000000,3.900000,180.000000,870.400000
75%,39.000000,57.500000,764.000000,18.300000,7.400000,123.000000,22.300000,94.000000,5.600000,281.000000,872.800000
max,164.400000,180.200000,3153.000000,107.300000,34.300000,226.000000,31.700000,100.000000,20.600000,360.000000,881.000000

In [9]:
data_numeric = data.select_dtypes(include="number")
data_numeric.corr()["pm2_5"]

pm2_5                   1.000000
pm10                    0.952177
carbon_monoxide         0.620771
nitrogen_dioxide        0.493972
sulphur_dioxide         0.753975
ozone                  -0.019743
temperature_2m         -0.522716
relative_humidity_2m    0.045576
wind_speed_10m         -0.110932
wind_direction_10m     -0.109160
surface_pressure        0.175934
Name: pm2_5, dtype: float64

In [10]:
data.duplicated().sum()

np.int64(0)